FROM python:3.12

WORKDIR /wattsdog_conector

COPY ./main.py .

COPY ./server.crt .

COPY ./server.key .

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PORT=5125
ENV ADMIN_PASSWORD=admin

EXPOSE 5125

CMD [ "python3", "main.py" ]